### ISSUE TITLE
[Pixel2][Oreo 8.1.0] DNS finder is stuck on oreo and unable to find anything.

### ISSUE THREAD

**Issue by amardeshbd** [andriydruk/RxDNSSD#38]
I'm using **Service Browser** app which I believe uses this library. When using `Pixel 2` device running on Android 8.1.0, the discovery seems to never discover any devices on the network.

Looking at the log does not give any clue. Attached related content. Let me know if you need more information.

Related resources
- LOG: [mdns-issue-pixel2-log.txt](https://github.com/andriydruk/RxDNSSD/files/1725296/mdns-issue-pixel2-log.txt)
- Screen Cap: ![mdns-issue-pixel2](https://user-images.githubusercontent.com/99822/36222870-a34b1e12-1190-11e8-8d9a-ff53818dd2bb.gif)
- Version: ![mdns-issue-pixel2-android-v8 1 0](https://user-images.githubusercontent.com/99822/36222807-7687ac60-1190-11e8-920c-99c7473654ce.png)

**Comment by amardeshbd** [comment]
Note: The app does work on Android 8.0.0 runnion on OnePlus 5.

**Comment by andriydruk** [comment]
Hi, I've just checked Pixel with 8.1.0 and all works fine
I guess this isssue is not about Oreo. Are you sure that device was connected to wifi network with at least 1 service? Did you check other applications?

From logs it looks like there are no issue with dnssd and no devices in current network

**Comment by Hossain-Khan-ConnectedLab** [comment]
hey @andriydruk I have tested with with Pixel 8.1.0 too, and it works without any issue.
Looks like it's hardware specific issue for Pixel 2 and Pixel 2 XL. 

Not sure how to capture data so that I can file to Google. Let me know what I should be looking at to report it to Google.

**Comment by amardeshbd** [comment]
hey @andriydruk I have tested with with Pixel 8.1.0 too, and it works without any issue.
Looks like it's hardware specific issue for Pixel 2 and Pixel 2 XL. Do you have access to any Pixel 2 devices?

Not sure how to capture data so that I can file to Google. Let me know what I should be looking at to report it to Google.

**Comment by erikos** [comment]
We likely seeing the same issue on a device, Pixel 2 with 8.1.0, where services can not be discovered. Was there any further find on the issue?

**Comment by amardeshbd** [comment]
@andriydruk One thing I observed is, if I use zero config app https://play.google.com/store/apps/details?id=com.melloware.zeroconf and launch it, then the  app immediately shows the devices in network.

After that if I switch back to **Service Browser** app, it also works immediately.

**Comment by andriydruk** [comment]
@amardeshbd I'm investigating this issue. Sorry, but I still can't find Pixel 2 or OnePlus 5 or HTC U11
I tried one of last Samsung [here](http://developer.samsung.com/remotetestlab/rtlDeviceList.action), but their don't have any services in networks there(
If you know similar services with remote testing please let me know

**Comment by amardeshbd** [comment]
@andriydruk Yes, that is correct. There is absolutely no indication of error/warning in the log that would say **why** the discovery is stuck. 😞 

I can try to re-run the library and capture log again with Pixel 2 and 2 XL. If I have time, I will try to debug the library and provide feedback if I have any.

**Comment by zarkooroz** [comment]
Just to add, we had same report for Pixel 2. I managed to get Pixel **2XL** and on that device service discovery was working just fine.
Here are the phone specs:
![img_20180406_103439 1](https://user-images.githubusercontent.com/16353664/38725162-bda1c402-3f06-11e8-8900-374ec5e42393.jpg)

**Comment by andriydruk** [comment]
@zarkooroz did you try DNSSDEmbedded?

**Comment by zarkooroz** [comment]
@andriydruk No, we are using DNSSDBindable. Current version is 0.9.5
Do you think that DNSSDEmbedded could solve the issue?

**Comment by andriydruk** [comment]
@zarkooroz Yes, embedded should work on any device - but might starts search little bit slower because it starts own version of mDNSReposnder instead of system

**Comment by andriydruk** [comment]
@zarkooroz mostly unwillingness to support it because on most devices Bindable works fine
But then I assumed that Google might broke system's mDNSReposnder in future versions of Android and undeprecated it.

**Comment by eman8519** [comment]
Hey guys....joining the fold here as well.  I have the same issue described here on a Pixel 2XL on 8.1.0, and have been troubleshooting for the past couple of days.  I have attempted DNSSDBindable, and DNSSDEmbedded.  I get the same results (or lack there of) with both.  I even took it a step further and attempted to use the core Android NsdManager.

Has anyone else here found a solution yet, I also am happy to help work on this issue as well, but don't want to step on top of any work already being done.

**Comment by eman8519** [comment]
For anyone interested in this I have found a workaround for this issue, though it may be something that Google has implemented on purpose for battery life, efficiency, or some other reason, I found that by explicitly requesting a Multicast lock begins allowing packets to be delivered again which allows RxDNSSD to work properly.

Be sure your `AndroidManifest.xml` contains:

```xml
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
````

Then when you start your discovery/browse function simple acquire a multicast lock like so:

```java
WifiManager wifi = (WifiManager) mContext.getSystemService(Context.WIFI_SERVICE);
WifiManager.MulticastLock multicastLock = wifi.createMulticastLock("multicastLock");
multicastLock.setReferenceCounted(true);
multicastLock.acquire();
```

Then teardown the lock once you complete your browsing:

```java
if (multicastLock != null) {
    multicastLock.release();
    multicastLock = null;
 }
```

@andriydruk I don't know how you feel about this being a part of this library, but if you would like for me to take a stab at it please let me know.  I'll be happy to add it in the appropriate places.  Part of me feels this is a workaround/hack, but another part of me thinks this could be deliberate from Google on the Pixel 2.

**Comment by amardeshbd** [comment]
That's an interesting find @eman8519 I will give it a try and provide feedback.

About putting it in the library, not sure if it feels right. If I remember correctly, it's not necessarily `8.1.0` specific issue. My OnePlus 5 got updated to `8.1.0` and it works on that phone.

**Comment by andriydruk** [comment]
Hi, @eman8519 
Thank you for your feedback.

As for me, I don't think it's a workaround or hack. It's logical that if mDnsResponder use multicasts for delivering packages, the library should ask system don't cut multicasts.

Actually, I thought about it at the moment of creating this library, but at that time there wasn't any issue connected to this, that's why I skipped lock to not overwhelm library.

I feel that we should add locks inside the library to prevent issues like this in future.

Correct places for lock [onServiceStarting](https://github.com/andriydruk/RxDNSSD/blob/master/library/src/main/java/com/github/druk/dnssd/DNSSDBindable.java#L38) and [onServiceStoping](https://github.com/andriydruk/RxDNSSD/blob/master/library/src/main/java/com/github/druk/dnssd/DNSSDBindable.java#L43). These methods would be called at every operations, that's why we need counter for runned operations. Take a look at embedded version, its already contains [mechanism for starting/stoping deamon](https://github.com/andriydruk/RxDNSSD/blob/master/library/src/main/java/com/github/druk/dnssd/DNSSDEmbedded.java#L129)

**Comment by andriydruk** [comment]
Hi, everyone
I've just published a new version. It includes wifi locks for all operations.
https://github.com/andriydruk/RxDNSSD/releases/tag/0.9.10

**Comment by kostadin24** [comment]
Well, I tried Service Browser on Samsung S8+ with android 8.1
Unfortunately problem with discovery still exist. Used last version 0.9.10
No errors in log.
Discovery works for 1-2 minutes after router reseting and stops. But other manifacturers still work.
